name: API Continuous Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '!api/.eslintrc.js'
      - '!api/server.js'

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Install serverless framework
        run: npm install serverless
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - name: Package
        run: serverless package
      - name: Deploy package
        run: serverless deploy --package .serverless
