name: API Continuous Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '!api/.eslintrc.js'
      - '!api/server.js'

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ./api
      - name: Change directory to api
        run: cd api
      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          BUCKET: ${{ secrets.BUCKET }}
          KEYPREFIX: ${{ secrets.KEYPREFIX }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DB_URI: ${{ secrets.DB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          HOST: ${{ secrets.HOST }}
          CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
