name: API Continuous Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '!api/.eslintrc.js'
      - '!api/server.js'

jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      BUCKET: ${{ secrets.BUCKET }}
      KEYPREFIX: ${{ secrets.KEYPREFIX }}
      DB_URI: ${{ secrets.DB_URI }}
      DB_NAME: ${{ secrets.DB_NAME }}
      HOST: ${{ secrets.HOST }}
      CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - mame: Install serverless framework
        run: npm install serverless
      - name: Serverless config credentials
        run: npm run config
      - name: Serverless package
        run: npm run package
      - name: Serverless deploy
        run: npm run deploy
